# SwiftLint Configuration for CloudSync Ultra
# https://github.com/realm/SwiftLint

# ─────────────────────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────────────────────

included:
  - CloudSyncApp

excluded:
  - CloudSyncAppTests
  - CloudSyncAppUITests
  - .build
  - DerivedData
  - Pods
  - Carthage
  - .swiftpm

# ─────────────────────────────────────────────────────────────────────────────
# Enabled Rules
# ─────────────────────────────────────────────────────────────────────────────

# Start with a reasonable set - not too strict for existing codebase
opt_in_rules:
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - modifier_order
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - yoda_condition

# ─────────────────────────────────────────────────────────────────────────────
# Disabled Rules
# ─────────────────────────────────────────────────────────────────────────────

disabled_rules:
  - trailing_comma              # Style preference - allow trailing commas
  - force_cast                  # Sometimes necessary with SwiftUI
  - force_try                   # Used in tests and known-safe contexts
  - todo                        # Allow TODOs - they're tracked in issues
  - opening_brace               # Can conflict with multiline formatting
  - nesting                     # SwiftUI views often have deep nesting

# ─────────────────────────────────────────────────────────────────────────────
# Rule Configuration
# ─────────────────────────────────────────────────────────────────────────────

# Line length - be reasonable for SwiftUI
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Type body length (classes, structs, enums)
type_body_length:
  warning: 300
  error: 500

# Function body length
function_body_length:
  warning: 60
  error: 100

# Function parameter count
function_parameter_count:
  warning: 6
  error: 8

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Type name length
type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]

# Identifier name length
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k
    - to
    - at
    - on
    - by
    - up
    - ok
    - ns
    - a
    - b
    - r
    - g
    # CodingKeys - standard Swift convention uses PascalCase
    - ID
    - Name
    - Path
    - Size
    - IsDir
    - ModTime
    - MimeType

# Large tuple
large_tuple:
  warning: 4
  error: 5

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

# Colon spacing
colon:
  apply_to_dictionaries: true

# Comma spacing
comma:
  severity: warning

# Statement position
statement_position:
  statement_mode: default
  severity: warning

# ─────────────────────────────────────────────────────────────────────────────
# Custom Rules
# ─────────────────────────────────────────────────────────────────────────────

# Custom rules disabled for now - enable as codebase is cleaned up
# custom_rules:
#   # Warn about print statements (should use Logger)
#   print_usage:
#     name: "Print Usage"
#     regex: "\\bprint\\s*\\("
#     message: "Consider using Logger instead of print() for production code"
#     severity: warning
#     match_kinds:
#       - identifier
#
#   # Discourage force unwrapping with !
#   force_unwrap_warning:
#     name: "Force Unwrap"
#     regex: "\\w+!"
#     message: "Avoid force unwrapping. Consider using guard, if let, or ?? instead"
#     severity: warning
#     match_kinds:
#       - identifier

# ─────────────────────────────────────────────────────────────────────────────
# Reporter
# ─────────────────────────────────────────────────────────────────────────────

reporter: "xcode"  # Use 'xcode' for Xcode integration, 'github-actions-logging' for CI
