#!/bin/bash
# Save session summary
# Usage: ./scripts/save-session.sh

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H%M)
SESSION_FILE=".claude-team/sessions/SESSION_${DATE}_${TIME}.md"

# Get current state
VERSION=$(cat VERSION.txt)
COMMITS=$(git log --oneline -5 2>/dev/null | sed 's/^/- /')
UNCOMMITTED=$(git status --short | wc -l | tr -d ' ')
TEST_COUNT=$(grep "^$DATE" .claude-team/metrics/test-counts.csv 2>/dev/null | tail -1 | cut -d, -f3 || echo "unknown")

cat > "$SESSION_FILE" << EOF
# Session Summary: $DATE

## Session Info
- **Date:** $DATE
- **Time:** $(date +%H:%M)
- **Version:** v$VERSION

## Recent Commits
$COMMITS

## State at Session End
- Tests: $TEST_COUNT
- Uncommitted changes: $UNCOMMITTED
- Branch: $(git branch --show-current)

## Notes
<!-- Add your session notes here -->


---
*Generated by save-session.sh*
EOF

echo "✅ Session saved to: $SESSION_FILE"
echo ""
echo "📝 Edit the file to add your notes:"
echo "   open $SESSION_FILE"
